services:
  - type: web
    name: megalodon-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_ID
        value: "MEGALODON~MD~v9JECKIB#SOaM3eVBeO8yJ_ZDTOA9dDX6qalU7PqJMRh2vaZ9U0M"
      - key: PREFIX
        value: "!"
      - key: BOT_NAME
        value: "â„³â„’ğ’¦â›·ï¸"
      - key: MODE
        value: "public"
      - key: OWNER_NUMBER
        value: "24102150515"
      - key: OWNER_NAME
        value: "â„ğ“ˆğ“‡ğ’¶ğ‘’Ìˆğ“âœ°"
      - key: DEV
        value: "24102150515"
      - key: AUTO_STATUS_REPLY
        value: "false"
      - key: AUTO_STATUS_MSG
        value: "*MEGALODON BOT VIEWED YOUR STATUS ğŸ¤–*"
      - key: READ_MESSAGE
        value: "false"
      - key: AUTO_REACT
        value: "false"
      - key: CUSTOM_REACT
        value: "false"
      - key: CUSTOM_REACT_EMOJIS
        value: "ğŸ’,ğŸ’–,ğŸ’—,â¤ï¸â€ğŸ©¹,â¤ï¸,ğŸ§¡,ğŸ’›,ğŸ’š,ğŸ’™,ğŸ’œ,ğŸ¤,ğŸ–¤,ğŸ¤"
      - key: STICKER_NAME
        value: "MEGALODON-MD"
      - key: AUTO_RECORDING
        value: "false"
      - key: AUTO_TYPING
        value: "false"
      - key: MENU_IMAGE_URL
        value: "https://files.catbox.moe/vh0ms9.jpg"
      - key: ANTI_BOT
        value: "false"
      - key: ANTI_DELETE
        value: "false"
      - key: ANTI_CALL
        value: "false"
      - key: REJECT_MSG
        value: "*ğŸ“ á´„Î±â„“â„“ É´ÏƒÑ‚ Î±â„“â„“ÏƒÏ‰Ñ”âˆ‚ Î¹É´ Ñ‚Ğ½Î¹Ñ• É´á´œĞ¼Ğ²Ñ”Ê€ ÑƒÏƒÏ… âˆ‚ÏƒÉ´Ñ‚ Ğ½Î±Î½Ñ” á´˜Ñ”Ê€Ğ¼Î¹Ñ•Ñ•Î¹Î¿É´ ğŸ“µ*"
      - key: ANTI_BAD
        value: "false"
      - key: ANTILINK_KICK
        value: "false"
      - key: ANTIVIEW_ONCE
        value: "true"
      - key: ANTILINK_WARN
        value: "false"
      - key: ANTILINK
        value: "true"
      - key: ANTI_VV
        value: "true"
      - key: DELETE_LINKS
        value: "true"
      - key: ANTI_DEL_PATH
        value: "false"
      - key: PUBLIC_MODE
        value: "true"
      - key: ALWAYS_ONLINE
        value: "false"
      - key: AUTO_STATUS_REACT
        value: "false"
      - key: AUTO_STATUS_SEEN
        value: "false"
      - key: AUTO_BIO
        value: "false"
      - key: WELCOME
        value: "true"
      - key: ADMIN_EVENTS
        value: "true"
